spring:
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:myDb;create=true
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher